# PlatformIO pre-script: read repo-root wifi.env and emit include/wifi_credentials.h
# wifi.env format (optional quotes): SSID="myssid"  PSK="secret"

from __future__ import annotations

import os
import re
import sys

Import("env")  # noqa: F821  # SCons injected


def _parse_wifi_env(path: str) -> tuple[str, str]:
    ssid: str | None = None
    psk: str | None = None
    assign_re = re.compile(r'^\s*(SSID|PSK)\s*=\s*(.*)\s*$')
    with open(path, "r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            m = assign_re.match(line)
            if not m:
                continue
            key, val = m.group(1), m.group(2).strip()
            if val.startswith('"'):
                end = val.rfind('"')
                val = val[1:end] if end > 1 else ""
            if key == "SSID":
                ssid = val
            else:
                psk = val
    if not ssid or not psk:
        raise ValueError("wifi.env must define non-empty SSID and PSK")
    return ssid, psk


def _c_string_literal(s: str) -> str:
    out: list[str] = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif 32 <= o <= 126:
            out.append(ch)
        else:
            out.append(f"\\u{o:04x}")
    return '"' + "".join(out) + '"'


project_dir = env["PROJECT_DIR"]
repo_root = os.path.abspath(os.path.join(project_dir, ".."))
wifi_path = os.path.join(repo_root, "wifi.env")
out_path = os.path.join(project_dir, "include", "wifi_credentials.h")

if not os.path.isfile(wifi_path):
    sys.stderr.write(f"[gen_wifi_credentials] ERROR: missing {wifi_path}\n")
    sys.stderr.write("Create TOPDIR/wifi.env with SSID=... and PSK=...\n")
    sys.exit(1)

try:
    ssid, psk = _parse_wifi_env(wifi_path)
except (OSError, UnicodeError, ValueError) as e:
    sys.stderr.write(f"[gen_wifi_credentials] ERROR: {e}\n")
    sys.exit(1)

lines = [
    "/* Generated by firmware/scripts/gen_wifi_credentials.py — do not edit. */",
    "#pragma once",
    "#include <cstdint>",
    "",
    "namespace cyd_wifi {",
    f"static constexpr char k_ssid[] = {_c_string_literal(ssid)};",
    f"static constexpr char k_psk[] = {_c_string_literal(psk)};",
    "}  // namespace cyd_wifi",
    "",
    "static constexpr uint16_t CYD_UDP_TELEM_PORT = 4210;",
    "",
]

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as out:
    out.write("\n".join(lines) + "\n")

print("[gen_wifi_credentials] wrote", out_path)
